# Generated by Django 5.2.16 on 2026-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('push', 'Push')], max_length=20),
        ),
    ]
