# Generated by Django 5.2.16 on 2026-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='actor_type',
            field=models.CharField(choices=[('user', 'User'), ('worker', 'Worker'), ('api_token', 'Api Token'), ('system', 'System'), ('anonymous', 'Anonymous')], default='system', max_length=20),
        ),
    ]
