{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulsegrid.fullname" . }}-worker
  labels:
    {{- include "pulsegrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "pulsegrid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "pulsegrid.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "pulsegrid.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: worker
          image: "{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"
          imagePullPolicy: {{ .Values.images.worker.pullPolicy }}
          env:
            - name: CONTROL_PLANE_URL
              value: {{ default (include "pulsegrid.webUrl" .) .Values.worker.controlPlaneUrl | quote }}
            - name: WORKER_CONCURRENCY
              value: {{ .Values.worker.concurrency | quote }}
            - name: WORKER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "worker.existingSecret is required when worker.enabled" .Values.worker.existingSecret }}
                  key: WORKER_TOKEN
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
