apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsegrid.fullname" . }}-web
  labels:
    {{- include "pulsegrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "pulsegrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsegrid.fullname" . }}-frontend
  labels:
    {{- include "pulsegrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "pulsegrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
