# Generated by Django 5.2.16 on 2026-07-10 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('monitor_type', models.CharField(choices=[('http', 'HTTP(S)'), ('tcp', 'TCP port')], default='http', max_length=10)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('expected_status', models.CharField(default='200-299', help_text="Comma-separated status codes or ranges, e.g. '200-299,301'", max_length=100)),
                ('keyword', models.CharField(blank=True, help_text='Response body must contain this', max_length=200)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('ssl_expiry_threshold_days', models.PositiveIntegerField(default=14, help_text='Alert when the certificate expires within this many days; 0 disables')),
                ('host', models.CharField(blank=True, max_length=500)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('timeout_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('failure_threshold', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('confirmations', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('regions', models.JSONField(blank=True, default=list)),
                ('is_paused', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.SlugField()),
                ('checked_at', models.DateTimeField()),
                ('ok', models.BooleanField()),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('dns_ms', models.FloatField(blank=True, null=True)),
                ('connect_ms', models.FloatField(blank=True, null=True)),
                ('tls_ms', models.FloatField(blank=True, null=True)),
                ('ttfb_ms', models.FloatField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorRegionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.SlugField()),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.FloatField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_states', to='monitors.monitor')),
            ],
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['organization', 'status'], name='monitors_mo_organiz_203c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['monitor', '-checked_at'], name='monitors_ch_monitor_24c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['checked_at'], name='monitors_ch_checked_55cbd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitorregionstate',
            unique_together={('monitor', 'region_code')},
        ),
    ]
