# Generated by Django 5.2.16 on 2026-07-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
