# Generated by Django 5.2.16 on 2026-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_alter_monitor_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='hop_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='hops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitor',
            name='hop_threshold_max',
            field=models.PositiveIntegerField(blank=True, help_text='Alert when the path is longer than this many hops; empty disables', null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='hop_threshold_min',
            field=models.PositiveIntegerField(blank=True, help_text='Alert when the path is shorter than this many hops; empty disables', null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='required_asn',
            field=models.PositiveBigIntegerField(blank=True, help_text='Alert when this BGP AS number is missing from the path; empty disables', null=True),
        ),
        migrations.AddField(
            model_name='monitorregionstate',
            name='last_hop_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[('http', 'HTTP(S)'), ('tcp', 'TCP port'), ('traceroute', 'Traceroute')], default='http', max_length=10),
        ),
    ]
